"""Reexporta la conexión PostgreSQL centralizada en database.py."""

from database import (
    DATABASE_KEY,
    DATABASE_URL,
    ROW_AS_DICT,
    SQL_FECHA_VENCIDA,
    SQL_INTERVAL_DAYS,
    SQL_INTERVAL_MONTHS,
    SQL_NOW,
    SQL_TODAY,
    SQL_VENCIMIENTO_30_DIAS,
    consultar_todos,
    consultar_uno,
    diagnosticar_postgresql,
    ejecutar_con_reintentos_bd,
    ejecutar_escritura,
    es_error_bd_transitorio,
    fila_a_dict,
    get_db_connection,
    normalizar_fila,
    normalizar_filas,
    normalizar_valor_columna,
    normalize_database_url,
    using_postgres,
)

__all__ = [
    'DATABASE_KEY',
    'DATABASE_URL',
    'ROW_AS_DICT',
    'SQL_FECHA_VENCIDA',
    'SQL_INTERVAL_DAYS',
    'SQL_INTERVAL_MONTHS',
    'SQL_NOW',
    'SQL_TODAY',
    'SQL_VENCIMIENTO_30_DIAS',
    'consultar_todos',
    'consultar_uno',
    'diagnosticar_postgresql',
    'ejecutar_con_reintentos_bd',
    'ejecutar_escritura',
    'es_error_bd_transitorio',
    'fila_a_dict',
    'get_db_connection',
    'normalizar_fila',
    'normalizar_filas',
    'normalizar_valor_columna',
    'normalize_database_url',
    'using_postgres',
]
